---
- name: General playbook to change password
  hosts: all
  become: true
  vars:
    myuser: "replace"
    mypassword: "password"
  tasks:
    - name: Change password on server
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{{ mypassword | password_hash('sha512') }}"
